import { Code } from 'lucide-react';
import {
  SiAmazonaws,
  SiApollographql,
  SiBootstrap,
  SiChakraui,
  SiCss3,
  SiDocker,
  SiExpress,
  SiFigma,
  SiFirebase,
  SiFramer,
  SiGit,
  SiGithub,
  SiGooglecloud,
  SiGraphql,
  SiHtml5,
  SiJavascript,
  SiJsonwebtokens,
  SiMongodb,
  SiMongoose,
  SiMui,
  SiMysql,
  SiNetlify,
  SiNextdotjs,
  SiNodedotjs,
  SiNpm,
  SiOpenai,
  SiPostgresql,
  SiPostman,
  SiPrisma,
  SiPython,
  SiReact,
  SiRedis,
  SiRedux,
  SiRender,
  SiSass,
  SiSocketdotio,
  SiStripe,
  SiSupabase,
  SiTailwindcss,
  SiTypescript,
  SiVercel,
  SiVite,
} from 'react-icons/si';

const normalizeSkillName = (name = '') => {
  return name.toLowerCase().replace(/[^a-z0-9]/g, '');
};

const skillIconMap = {
  react: { icon: SiReact, color: '#61DAFB' },
  reactjs: { icon: SiReact, color: '#61DAFB' },
  next: { icon: SiNextdotjs, color: '#ffffff' },
  nextjs: { icon: SiNextdotjs, color: '#ffffff' },
  node: { icon: SiNodedotjs, color: '#5FA04E' },
  nodejs: { icon: SiNodedotjs, color: '#5FA04E' },
  express: { icon: SiExpress, color: '#ffffff' },
  expressjs: { icon: SiExpress, color: '#ffffff' },
  mongodb: { icon: SiMongodb, color: '#47A248' },
  mongoose: { icon: SiMongoose, color: '#880000' },
  mysql: { icon: SiMysql, color: '#4479A1' },
  postgresql: { icon: SiPostgresql, color: '#4169E1' },
  postgres: { icon: SiPostgresql, color: '#4169E1' },
  redis: { icon: SiRedis, color: '#FF4438' },
  tailwind: { icon: SiTailwindcss, color: '#06B6D4' },
  tailwindcss: { icon: SiTailwindcss, color: '#06B6D4' },
  html: { icon: SiHtml5, color: '#E34F26' },
  html5: { icon: SiHtml5, color: '#E34F26' },
  css: { icon: SiCss3, color: '#1572B6' },
  css3: { icon: SiCss3, color: '#1572B6' },
  javascript: { icon: SiJavascript, color: '#F7DF1E' },
  js: { icon: SiJavascript, color: '#F7DF1E' },
  typescript: { icon: SiTypescript, color: '#3178C6' },
  ts: { icon: SiTypescript, color: '#3178C6' },
  python: { icon: SiPython, color: '#3776AB' },
  graphql: { icon: SiGraphql, color: '#E10098' },
  apollographql: { icon: SiApollographql, color: '#311C87' },
  openai: { icon: SiOpenai, color: '#ffffff' },
  chatgpt: { icon: SiOpenai, color: '#ffffff' },
  redux: { icon: SiRedux, color: '#764ABC' },
  vite: { icon: SiVite, color: '#646CFF' },
  framer: { icon: SiFramer, color: '#ffffff' },
  framermotion: { icon: SiFramer, color: '#ffffff' },
  bootstrap: { icon: SiBootstrap, color: '#7952B3' },
  sass: { icon: SiSass, color: '#CC6699' },
  mui: { icon: SiMui, color: '#007FFF' },
  materialui: { icon: SiMui, color: '#007FFF' },
  chakraui: { icon: SiChakraui, color: '#319795' },
  firebase: { icon: SiFirebase, color: '#FFCA28' },
  supabase: { icon: SiSupabase, color: '#3FCF8E' },
  prisma: { icon: SiPrisma, color: '#2D3748' },
  socketio: { icon: SiSocketdotio, color: '#ffffff' },
  stripe: { icon: SiStripe, color: '#635BFF' },
  jwt: { icon: SiJsonwebtokens, color: '#ffffff' },
  jsonwebtoken: { icon: SiJsonwebtokens, color: '#ffffff' },
  git: { icon: SiGit, color: '#F05032' },
  github: { icon: SiGithub, color: '#ffffff' },
  docker: { icon: SiDocker, color: '#2496ED' },
  postman: { icon: SiPostman, color: '#FF6C37' },
  npm: { icon: SiNpm, color: '#CB3837' },
  figma: { icon: SiFigma, color: '#F24E1E' },
  vercel: { icon: SiVercel, color: '#ffffff' },
  render: { icon: SiRender, color: '#46E3B7' },
  netlify: { icon: SiNetlify, color: '#00C7B7' },
  aws: { icon: SiAmazonaws, color: '#FF9900' },
  amazonaws: { icon: SiAmazonaws, color: '#FF9900' },
  googlecloud: { icon: SiGooglecloud, color: '#4285F4' },
  gcp: { icon: SiGooglecloud, color: '#4285F4' },
};

export const getSkillIcon = (name) => {
  return skillIconMap[normalizeSkillName(name)] || {
    icon: Code,
    color: '#60A5FA',
  };
};
